export const COUNTRIES = [
  { code: "IN", flag: "🇮🇳", name: "India", dial: "+91" },
  { code: "US", flag: "🇺🇸", name: "United States", dial: "+1" },
  { code: "GB", flag: "🇬🇧", name: "United Kingdom", dial: "+44" },
  { code: "CA", flag: "🇨🇦", name: "Canada", dial: "+1" },
  { code: "AE", flag: "🇦🇪", name: "UAE", dial: "+971" },
  { code: "AU", flag: "🇦🇺", name: "Australia", dial: "+61" },
  { code: "SG", flag: "🇸🇬", name: "Singapore", dial: "+65" },
  { code: "DE", flag: "🇩🇪", name: "Germany", dial: "+49" },
  { code: "FR", flag: "🇫🇷", name: "France", dial: "+33" },
  { code: "JP", flag: "🇯🇵", name: "Japan", dial: "+81" },
  { code: "BR", flag: "🇧🇷", name: "Brazil", dial: "+55" },
  { code: "MY", flag: "🇲🇾", name: "Malaysia", dial: "+60" },
  { code: "ZA", flag: "🇿🇦", name: "South Africa", dial: "+27" },
];
